name: Test and Build

on:
  # Runs on pushes to master (development branch)
  push:
    branches: ['master']

  # Runs on pull requests to master
  pull_request:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build check
        run: npm run build